---
version: "3.7"

services:

  eo_tools:
      build: 
        context: .
        dockerfile: Dockerfile
      environment:
        PYTHONPATH: /eo_tools
      volumes:
        - ${HOME}/eo_tools:/eo_tools
        - ${HOME}/data:/data
        # Overrides default command so things don't shut down after the process ends.
      command: /bin/sh -c "while sleep 1000; do :; done" 

  stac-fastapi:
    # Note:
    # the official ghcr.io/stac-utils/stac-fastapi-pgstac image uses python 3.8 and uvicorn
    # which is why here we use a custom Dockerfile using python 3.11 and gunicorn
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.stac
    ports:
      - "127.0.0.1:8081:8081"
    user: 1000:1000
    environment:
      # Application
      - HOST=0.0.0.0
      - PORT=8081
      - MODULE_NAME=stac_fastapi.pgstac.app
      - VARIABLE_NAME=app
      # gunicorn
      # https://github.com/tiangolo/uvicorn-gunicorn-docker#web_concurrency
      - WEB_CONCURRENCY=10
      # https://github.com/tiangolo/uvicorn-gunicorn-docker#workers_per_core
      # - WORKERS_PER_CORE=1
      # https://github.com/tiangolo/uvicorn-gunicorn-docker#max_workers
      # - MAX_WORKERS=10
      # Postgres connection
      - POSTGRES_USER=stacapi
      - POSTGRES_PASS=$DB_PASS
      - POSTGRES_DBNAME=postgis
      - POSTGRES_HOST_READER=database
      - POSTGRES_HOST_WRITER=database
      - POSTGRES_PORT=5432
      - DB_MIN_CONN_SIZE=1
      - DB_MAX_CONN_SIZE=10
    depends_on:
      - database
    command:
      bash -c "bash /tmp/scripts/wait-for-it.sh -t 120 -h database -p 5432 && /start.sh"
    volumes:
      - ./dockerfiles/scripts:/tmp/scripts

  database:
    image: ghcr.io/stac-utils/pgstac:v0.8.1
    user: 1000:1000
    environment:
      - POSTGRES_USER=stacapi
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=postgis
      - PGUSER=stacapi
      - PGPASSWORD=$DB_PASS
      - PGDATABASE=postgis
    ports:
      - 127.0.0.1:5439:5432
    command: postgres -N 500
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
