name: s1_proc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - tqdm
  - gdal
  - pyroSAR
  - spatialist
  - pip
  - pystac
  - geopandas
  - pandas
  - asf_search
  - ipykernel
