name: eo_tools
channels:
  # - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pyproj
  - pytest
  - gdal
  - libgdal-jp2openjpeg
  - rasterio
  - pyrosar
  - spatialist
  - pip
  - pystac
  - pystac-client
  - geopandas
  - pandas
  - eodag=2.12.1
  - ipykernel
  - ipywidgets
  - black
  - scikit-image
  - ipyleaflet
  - folium
  - tqdm
  - xmltodict
  - httpx
  - xarray
  - netcdf4
  - rioxarray=0.17.0
  - numba
  - dask
  - bottleneck
  # these are required to avoid eodag to break
  - websockets 
  - watchfiles 
  - uvloop 
  - python-dotenv 
  - httptools
  - planetary-computer
  # - numexpr
  # - pip:
    # - titiler.application
    # - eodag
  # - memory_profiler
