name: s1_proc
channels:
  - conda-forge
  # - terradue
  - defaults
dependencies:
  - python>=3.8
  - tqdm
  - gdal
  - rasterio
  - pyroSAR
  - spatialist
  - pip
  - pystac
  - geopandas
  - pandas
  - asf_search
  - ipykernel
  - black
  - rio-cogeo
  # - snapista
  - scikit-image
  - sentinelsat 
