name: eo_tools
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - gdal
  - rasterio
  - pyroSAR
  - spatialist
  - pip
  - pystac
  - geopandas
  - pandas
  - ipykernel
  - ipywidgets
  - black
  - scikit-image
  - eodag
  - ipyleaflet
  - folium
  - tqdm
  - xmltodict
  - httpx
  - xarray
  - netcdf4
  - rioxarray
  - numba
