name: eo_tools
channels:
- conda-forge
- pkgs/main
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- affine=2.3.0
- annotated-types=0.6.0
- anyio=4.2.0
- anyjson=0.3.3
- aom=3.9.0
- argon2-cffi=21.3.0
- argon2-cffi-bindings=21.2.0
- arrow=1.2.3
- asttokens=2.0.5
- attrs=23.1.0
- aws-c-auth=0.7.20
- aws-c-cal=0.6.12
- aws-c-common=0.9.17
- aws-c-compression=0.2.18
- aws-c-event-stream=0.4.2
- aws-c-http=0.8.1
- aws-c-io=0.14.8
- aws-c-mqtt=0.10.4
- aws-c-s3=0.5.8
- aws-c-sdkutils=0.1.16
- aws-checksums=0.1.18
- aws-crt-cpp=0.26.8
- aws-sdk-cpp=1.11.267
- azure-core-cpp=1.11.1
- azure-identity-cpp=1.6.0
- azure-storage-blobs-cpp=12.10.0
- azure-storage-common-cpp=12.5.0
- babel=2.11.0
- bcrypt=3.2.0
- black=24.3.0
- blas=1.0
- blosc=1.21.5
- bokeh=3.4.0
- boto3=1.34.82
- botocore=1.34.82
- bottleneck=1.3.7
- branca=0.6.0
- brotli=1.0.9
- brotli-python=1.0.9
- brunsli=0.1
- bzip2=1.0.8
- c-ares=1.28.1
- c-blosc2=2.14.4
- ca-certificates=2024.3.11
- cads-api-client=1.0.3
- cairo=1.18.0
- cdsapi=0.7.0
- certifi=2024.2.2
- cffi=1.16.0
- cfitsio=4.4.0
- cftime=1.6.2
- charls=2.4.2
- charset-normalizer=2.0.4
- click=8.1.7
- click-plugins=1.1.1
- cligj=0.7.2
- cloudpickle=2.2.1
- colour=0.1.4
- comm=0.2.1
- contourpy=1.2.0
- cryptography=42.0.5
- cycler=0.11.0
- cytoolz=0.12.2
- dask=2024.5.0
- dask-core=2024.5.0
- dask-expr=1.1.0
- dataclasses=0.8
- dav1d=1.2.1
- debugpy=1.6.7
- decorator=5.1.1
- dill=0.3.8
- distributed=2024.5.0
- ecmwf-api-client=1.6.3
- eodag=2.12.1
- executing=0.8.3
- expat=2.6.2
- fastapi=0.103.0
- fiona=1.9.6
- fmt=10.2.1
- folium=0.14.0
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=2.001
- font-ttf-source-code-pro=2.030
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-anaconda=1
- fonts-conda-ecosystem=1
- fonttools=4.51.0
- freetype=2.12.1
- freexl=2.0.0
- fsspec=2024.3.1
- furl=2.1.2
- gdal=3.8.5
- geoalchemy2=0.9.2
- geojson=3.1.0
- geopandas=0.14.2
- geopandas-base=0.14.2
- geos=3.12.1
- geotiff=1.7.1
- gflags=2.2.2
- giflib=5.2.2
- glog=0.7.0
- gmp=6.2.1
- greenlet=3.0.1
- h11=0.14.0
- hdf4=4.2.15
- hdf5=1.14.3
- heapdict=1.0.1
- httpcore=1.0.2
- httpx=0.26.0
- icu=73.2
- idna=3.7
- imagecodecs=2024.1.1
- imageio=2.33.1
- infinity=1.5
- iniconfig=1.1.1
- intervals=0.9.2
- ipykernel=6.28.0
- ipyleaflet=0.17.4
- ipython=8.20.0
- ipywidgets=8.1.2
- jedi=0.18.1
- jinja2=3.1.3
- jmespath=1.0.1
- joblib=1.4.0
- json-c=0.17
- jsonpath-ng=1.5.3
- jupyter_client=8.6.0
- jupyter_core=5.5.0
- jupyterlab_widgets=3.0.10
- jxrlib=1.1
- kealib=1.5.3
- keyutils=1.6.1
- kiwisolver=1.4.4
- krb5=1.21.2
- lazy_loader=0.3
- lcms2=2.16
- ld_impl_linux-64=2.38
- lerc=4.0.0
- libabseil=20240116.2
- libaec=1.1.3
- libarchive=3.7.2
- libarrow=16.1.0
- libarrow-acero=16.1.0
- libarrow-dataset=16.1.0
- libarrow-substrait=16.1.0
- libavif16=1.0.4
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcrc32c=1.1.2
- libcurl=8.7.1
- libdeflate=1.20
- libedit=3.1.20230828
- libev=4.33
- libevent=2.1.12
- libexpat=2.6.2
- libffi=3.4.4
- libgcc-ng=13.2.0
- libgdal=3.8.5
- libgfortran-ng=13.2.0
- libgfortran5=13.2.0
- libglib=2.80.2
- libgomp=13.2.0
- libgoogle-cloud=2.23.0
- libgoogle-cloud-storage=2.23.0
- libgrpc=1.62.2
- libhwy=1.1.0
- libiconv=1.17
- libjpeg-turbo=3.0.0
- libjxl=0.10.2
- libkml=1.3.0
- libllvm14=14.0.6
- libnetcdf=4.9.2
- libnghttp2=1.58.0
- libnsl=2.0.1
- libopenblas=0.3.21
- libparquet=16.1.0
- libpng=1.6.43
- libpq=16.3
- libprotobuf=4.25.3
- libre2-11=2023.09.01
- librttopo=1.1.0
- libsodium=1.0.18
- libspatialindex=1.9.3
- libspatialite=5.1.0
- libsqlite=3.45.3
- libssh2=1.11.0
- libstdcxx-ng=13.2.0
- libthrift=0.19.0
- libtiff=4.6.0
- libutf8proc=2.8.0
- libuuid=2.38.1
- libwebp-base=1.4.0
- libxcb=1.15
- libxcrypt=4.4.36
- libxml2=2.12.7
- libxslt=1.1.39
- libzip=1.10.1
- libzlib=1.2.13
- libzopfli=1.0.3
- llvmlite=0.42.0
- locket=1.0.0
- lxml=5.2.2
- lz4=4.3.2
- lz4-c=1.9.4
- lzo=2.10
- mapclassify=2.5.0
- markupsafe=2.1.3
- matplotlib-base=3.8.4
- matplotlib-inline=0.1.6
- minizip=4.0.3
- msgpack-python=1.0.3
- multiprocess=0.70.15
- multiurl=0.3.1
- mypy_extensions=1.0.0
- ncurses=6.5
- nest-asyncio=1.6.0
- netcdf4=1.6.5
- networkx=3.1
- nspr=4.35
- nss=3.100
- numba=0.59.1
- numexpr=2.8.7
- numpy=1.26.4
- numpy-base=1.26.4
- openjpeg=2.5.2
- openssl=3.3.0
- orc=2.0.0
- orderedmultidict=1.0.1
- orjson=3.9.15
- owslib=0.31.0
- packaging=23.2
- pandas=2.1.4
- parso=0.8.3
- partd=1.4.1
- passlib=1.7.4
- pathos=0.3.0
- pathspec=0.10.3
- pcre2=10.43
- pendulum=2.1.2
- pexpect=4.8.0
- phonenumbers=8.12.27
- pillow=10.3.0
- pip=24.0
- pixman=0.43.2
- platformdirs=3.10.0
- pluggy=1.0.0
- ply=3.11
- poppler=24.04.0
- poppler-data=0.4.11
- postgresql=16.3
- pox=0.3.3
- ppft=1.7.6.7
- progressbar2=4.2.0
- proj=9.4.0
- prompt-toolkit=3.0.43
- prompt_toolkit=3.0.43
- psutil=5.9.0
- psycopg2=2.9.9
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pyarrow=16.1.0
- pyarrow-core=16.1.0
- pybind11-abi=5
- pycparser=2.21
- pycryptodome=3.15.0
- pydantic=2.5.3
- pydantic-core=2.14.6
- pygments=2.15.1
- pyparsing=3.0.9
- pyproj=3.6.1
- pyrosar=0.24.0
- pyshp=2.3.1
- pysocks=1.7.1
- pystac=1.10.1
- pytest=7.4.0
- python=3.12.3
- python-dateutil=2.9.0post0
- python-lmdb=1.4.1
- python-tzdata=2023.3
- python-utils=3.3.3
- python_abi=3.12
- pytz=2024.1
- pytzdata=2020.1
- pyyaml=6.0.1
- pyzmq=25.1.2
- rasterio=1.3.10
- rav1e=0.6.6
- re2=2023.09.01
- readline=8.2
- requests=2.31.0
- requests-ftp=0.3.1
- requests-futures=1.0.0
- rioxarray=0.15.5
- rtree=1.0.1
- s2n=1.4.13
- s3transfer=0.10.1
- scikit-image=0.22.0
- scikit-learn=1.4.2
- scipy=1.13.0
- setuptools=69.5.1
- setuptools-scm=8.0.4
- setuptools_scm=8.0.4
- shapely=2.0.4
- six=1.16.0
- snappy=1.2.0
- sniffio=1.3.0
- snuggs=1.4.7
- sortedcontainers=2.4.0
- spatialist=0.13.1
- spdlog=1.13.0
- sqlalchemy=1.4.49
- sqlalchemy-utils=0.37.8
- sqlite=3.45.3
- stack_data=0.2.0
- starlette=0.27.0
- stream-zip=0.0.71
- svt-av1=2.1.0
- tblib=1.7.0
- threadpoolctl=2.2.0
- tifffile=2023.4.12
- tiledb=2.23.0
- tk=8.6.14
- toolz=0.12.0
- tornado=6.3.3
- tqdm=4.66.2
- traitlets=5.7.1
- traittypes=0.2.1
- typing-extensions=4.11.0
- typing_extensions=4.11.0
- tzcode=2024a
- tzdata=2024a
- unicodedata2=15.1.0
- uriparser=0.9.7
- urllib3=2.2.1
- usgs=0.3.5
- uvicorn=0.20.0
- wcwidth=0.2.5
- wheel=0.43.0
- whoosh=2.7.4
- widgetsnbextension=4.0.10
- xarray=2023.6.0
- xerces-c=3.2.5
- xmltodict=0.13.0
- xorg-kbproto=1.0.7
- xorg-libice=1.1.1
- xorg-libsm=1.2.4
- xorg-libx11=1.8.9
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.11
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xyzservices=2022.9.0
- xz=5.4.6
- yaml=0.2.5
- zeromq=4.3.5
- zfp=1.0.1
- zict=3.0.0
- zlib=1.2.13
- zlib-ng=2.0.7
- zstd=1.5.6

