name: s1_proc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  # - tqdm
  - gdal
  - rasterio
  - pyroSAR
  - spatialist
  - pip
  - pystac
  - geopandas
  - pandas
  - asf_search
  - ipykernel
  - black
  - rio-cogeo
  - scikit-image
  - sentinelsat 
