name: s1_proc
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - gdal
  - rasterio
  - pyroSAR
  - spatialist
  - pip
  - pystac
  - geopandas
  - pandas
  - asf_search
  - ipykernel
  - ipywidgets
  - black
  - rio-cogeo
  - scikit-image
  - sentinelsat 
  - localtileserver 
  - ipyleaflet
  - tqdm
  - eodag
