[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "eo_tools"
version = "2024.10.1"
description = "A toolbox for easily searching, downloading & processing remote sensing imagery from various public sources. "
dependencies = ["python==3.12.7", "pytest==8.3.3", "gdal==3.9.2", "rasterio==1.3.11", "pyrosar==0.24.0", "spatialist==0.14.0", "pip==24.2", "pystac==1.11.0", "pystac-client==0.8.4", "geopandas==1.0.1", "pandas==2.2.3", "eodag==2.12.1", "ipykernel==6.29.5", "ipywidgets==8.1.5", "black==24.10.0", "scikit-image==0.24.0", "ipyleaflet==0.19.2", "folium==0.17.0", "tqdm==4.66.5", "xmltodict==0.14.2", "httpx==0.27.2", "xarray==2024.9.0", "netcdf4==1.7.1", "rioxarray==0.17.0", "numba==0.60.0", "dask==2024.9.1", "bottleneck==1.4.1", "websockets==13.1", "watchfiles==0.24.0", "uvloop==0.21.0", "python-dotenv==1.0.1", "httptools==0.6.1", "planetary-computer==1.0.0"]
[[project.authors]]
name = "Olivier D'Hondt"
email = "dhondt.olivier@gmail.com"

[tool.setuptools]
packages = [ "eo_tools", "eo_tools.S1",]
include-package-data = true
