[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "eo_tools"
version = "test"
description = "Description of your package"
dependencies = [ "python", "pytest", "gdal", "rasterio", "spatialist", "pip", "pystac", "pystac-client", "geopandas", "pandas", "ipykernel", "ipywidgets", "black", "scikit-image", "ipyleaflet", "folium", "tqdm", "xmltodict", "httpx", "xarray", "netcdf4", "rioxarray", "numba", "dask", "bottleneck",]
[[project.authors]]
name = "Olivier D'Hondt"
email = "dhondt.olivier@gmail.com"

[tool.setuptools]
include-package-data = true

