[build-system]
requires = [ "setuptools", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "eo_tools"
version = "2024.8.1"
description = "A toolbox for easily searching, downloading & processing remote sensing imagery from various public sources. "
dependencies = ["python==3.12.5", "pytest==8.3.2", "gdal==3.9.2", "rasterio==1.3.10", "pyrosar==0.24.0", "spatialist==0.13.1", "pip==24.2", "pystac==1.10.1", "pystac-client==0.8.3", "geopandas==1.0.1", "pandas==2.2.2", "eodag==2.12.1", "ipykernel==6.29.5", "ipywidgets==8.1.5", "black==24.8.0", "scikit-image==0.24.0", "ipyleaflet==0.19.2", "folium==0.17.0", "tqdm==4.66.5", "xmltodict==0.13.0", "httpx==0.27.0", "xarray==2024.7.0", "netcdf4==1.7.1", "rioxarray==0.17.0", "numba==0.60.0", "dask==2024.8.1", "bottleneck==1.4.0", "websockets==13.0", "watchfiles==0.23.0", "uvloop==0.20.0", "python-dotenv==1.0.1", "httptools==0.6.1", "numexpr==2.10.0"]
[[project.authors]]
name = "Olivier D'Hondt"
email = "dhondt.olivier@gmail.com"

[tool.setuptools]
packages = [ "eo_tools", "eo_tools.S1",]
include-package-data = true
