services:
  eo_tools_package_test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PYTHONPATH: /eo_tools
    volumes:
      - ../../tests:/eo_tools/tests:ro
      - ../../scripts:/eo_tools/scripts:ro
      - ../../data:/eo_tools/data:ro
      - ../../notebooks:/eo_tools/notebooks:ro
      - ../../notebooks-cf:/eo_tools/notebooks-cf:ro
      - ../../eo_tools_dev:/eo_tools/eo_tools_dev:ro
      - ${HOME}/data:/data
    command: sleep infinity
    network_mode: host

  titiler:
    image: ghcr.io/developmentseed/titiler:latest
    environment:
      HOST: 127.0.0.1
      PORT: 8085
      WEB_CONCURRENCY: 1
      WORKERS_PER_CORE: 1
      CPL_TMPDIR: /tmp
      GDAL_CACHEMAX: 75%
      GDAL_INGESTED_BYTES_AT_OPEN: 32768
      GDAL_DISABLE_READDIR_ON_OPEN: EMPTY_DIR
      GDAL_HTTP_MERGE_CONSECUTIVE_RANGES: "YES"
      GDAL_HTTP_MULTIPLEX: "YES"
      GDAL_HTTP_VERSION: "2"
      PYTHONWARNINGS: ignore
      VSI_CACHE: "TRUE"
      VSI_CACHE_SIZE: 536870912
      LOG_LEVEL: debug
    volumes:
      - ${HOME}/data:/data
    network_mode: host
